name: grabers-2020
recipe: drupal8
config:
  webroot: ./web
  php: '7.2'
  xdebug: false
  config:
    php: php.ini
services:
  node:
    type: node
    build:
      - npm install
      - gulp
    globals:
      gulp-cli: "latest"
  pma:
    type: phpmyadmin
    hosts:
      - database
tooling:
  npm:
    service: node
  node:
    service: node
  gulp:
    service: node